name: Check Upstream Version

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./.github/scripts/acng-upstream-version-checker
          
      - name: Check for updates
        id: check
        run: python .github/scripts/check_version.py .github/CURRENT_UPSTREAM_VERSION
        continue-on-error: true

      - name: Commit and push if updated
        if: steps.check.outcome == 'success'
        run: python .github/scripts/git_push.py .github/CURRENT_UPSTREAM_VERSION